### PR TITLE
Update Constants.java to ignore vim swap file

### PR DESCRIPTION
**Pull request by hashar**

### CODE REVIEW

**Comment by hashar** [comment]
The file was referred to from https://github.com/ec4j/editorconfig-maven-plugin#basic-usage

**Review by ppalaga — APPROVED** [review]
Thanks  @hashar!

**Comment by hashar** [comment]
I am am quite happy to have found the proper java file to edit. Thank you for the code approval!

**Comment by ppalaga** [comment]
I released 2.2.2

**Pull request merged**
